import { useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowRight, Bell, Blocks, CalendarDays, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Command, Ellipsis, FileText, FolderKanban, Gauge, LayoutDashboard, ListTodo, Menu, MessageCircle, Plus, Search, Settings2, ShieldAlert, Sparkles, Users, X } from 'lucide-react';

const initialTasks = [
  { title: 'Final review widoku płatności', project: 'Northstar · Mobile app', due: 'Dziś, 14:00', initials: 'MK', color: 'lavender', done: false },
  { title: 'Potwierdzić scope sprintu 12', project: 'Acme · Platforma B2B', due: 'Dziś, 16:30', initials: 'AK', color: 'mint', done: false },
  { title: 'Wysłać podsumowanie statusu', project: 'Bloom · E-commerce', due: 'Jutro, 10:00', initials: 'JL', color: 'peach', done: false },
];
const projects = [
  { client: 'NORTHSTAR', name: 'Aplikacja mobilna', tag: 'Mobile app', stage: 'Development', progress: 72, days: '18 dni do launchu', initials: 'NS', tone: 'blue', people: ['MK','AK','JL'], budget: '82%', status: 'On track', statusTone: 'green', date: '24 paź' },
  { client: 'ACME CORP.', name: 'Platforma B2B', tag: 'Web platform', stage: 'Sprint 12', progress: 48, days: 'Sprint kończy się za 4 dni', initials: 'A', tone: 'orange', people: ['AK','TB','MK'], budget: '94%', status: 'Uwaga', statusTone: 'amber', date: '31 paź' },
  { client: 'BLOOM STUDIO', name: 'Sklep internetowy', tag: 'E-commerce', stage: 'QA & testing', progress: 91, days: 'Gotowe do odbioru', initials: 'B', tone: 'pink', people: ['JL','MK'], budget: '76%', status: 'On track', statusTone: 'green', date: '18 paź' },
];
const updates = [
 { initials:'MK', tone:'lavender', who:'Marta Kowalska', action:'dodała komentarz do', subject:'Płatności · widok mobile', when:'12 min temu', text:'„Na iOS pole przyjmuje tylko cyfry — poprawione i gotowe do ponownego review.”', icon: MessageCircle },
 { initials:'TB', tone:'mint', who:'Tomek Baran', action:'zmienił status zadania', subject:'Integracja z ERP', when:'48 min temu', text:'W trakcie → Do review', icon: CheckCheck },
 { initials:'JL', tone:'peach', who:'Julia Lewandowska', action:'dodała plik do', subject:'Bloom · dokumentacja QA', when:'2 godz. temu', text:'Checklist_release_v2.pdf · 2,4 MB', icon: FileText },
];
const nav = [{ label:'Workspace', items:[['Overview',LayoutDashboard],['Projekty',FolderKanban,'3'],['Zadania',ListTodo,'8'],['Kalendarz',CalendarDays]] },{ label:'ZESPÓŁ', items:[['Klienci',Users],['Raporty',Activity]] }];

function App(){
 const [section,setSection]=useState('Overview'),[tasks,setTasks]=useState(initialTasks),[projectList,setProjectList]=useState(projects),[search,setSearch]=useState(''),[filter,setFilter]=useState('Wszystkie'),[showModal,setShowModal]=useState(false),[menuOpen,setMenuOpen]=useState(false),[toast,setToast]=useState('');
 const filtered=useMemo(()=>projectList.filter(p=>(`${p.client} ${p.name} ${p.tag}`).toLowerCase().includes(search.toLowerCase())),[search,projectList]);
 const visibleTasks=tasks.map((task,index)=>({...task,index})).filter(task=>filter==='Wszystkie'||(filter==='Dziś'?task.due.startsWith('Dziś'):task.due.startsWith('Wczoraj')));
 const notify=(message)=>{setToast(message);window.setTimeout(()=>setToast(''),2600)};
 const toggleTask=(i)=>setTasks(prev=>prev.map((t,n)=>n===i?{...t,done:!t.done}:t));
 return <div className="shell">
  <aside className={`sidebar ${menuOpen?'open':''}`}>
   <div className="brand"><div className="brand-icon"><Blocks size={19}/></div><span>orbit<span className="brand-dot">.</span></span><button className="mobile-close" onClick={()=>setMenuOpen(false)}><X size={18}/></button></div>
   <button className="workspace-switch"><div className="workspace-mark">S</div><div className="workspace-copy"><b>Studio North</b><small>Workspace</small></div><ChevronDown size={15}/></button>
   <div className="nav-scroll">{nav.map(group=><div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(([label,Icon,count])=><button key={label} onClick={()=>{setSection(label);setMenuOpen(false)}} className={`nav-item ${section===label?'selected':''}`}><Icon size={17}/><span>{label}</span>{count&&<span className="nav-count">{count}</span>}</button>)}</div>)}
    <div className="nav-group"><div className="nav-label">OSTATNIE PROJEKTY</div>{projectList.slice(0,3).map(p=><button key={p.client} className="nav-project" onClick={()=>setSection('Projekty')}><i className={`tiny-dot ${p.tone}`}/><span>{p.name}</span></button>)}</div>
   </div>
   <div className="sidebar-bottom"><div className="plan-card"><div className="plan-top"><span>Twój plan</span><span>75%</span></div><div className="plan-track"><i/></div><small>Wykorzystano 3 z 4 projektów</small><button onClick={()=>notify('Szczegóły planu będą dostępne wkrótce.')}>Zobacz plan <ArrowRight size={13}/></button></div><button className="nav-item"><Settings2 size={17}/><span>Ustawienia</span></button><div className="profile"><div className="avatar avatar-me">PK</div><div className="profile-copy"><b>Piotr Kowalski</b><small>Project Manager</small></div><Ellipsis size={18}/></div></div>
  </aside>
  {menuOpen&&<div className="scrim" onClick={()=>setMenuOpen(false)}/>}
  <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenuOpen(true)}><Menu size={19}/></button><div className="breadcrumbs"><span>Studio North</span><span className="slash">/</span><b>{section}</b></div><div className="top-actions"><div className="searchbox"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Szukaj projektu, zadania..."/><kbd><Command size={11}/> K</kbd></div><button className="icon-button notification" onClick={()=>notify('Nie masz nowych powiadomień.')} aria-label="Powiadomienia"><Bell size={18}/><i/></button><span className="top-divider"/><div className="avatar avatar-me top-avatar">PK</div></div></header>
   <div className="content"><section className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> PIĄTEK, 2 PAŹDZIERNIKA 2026</div><h1>Dzień dobry, Piotr <span>✳</span></h1><p>Oto co dzieje się w Twoim workspace.</p></div><button className="primary-button" onClick={()=>setShowModal(true)}><Plus size={17}/> Nowy projekt</button></section>
   <section className="stats-grid"><Stat icon={FolderKanban} label="Aktywne projekty" value={projectList.length} foot="Wszystkie w terminie" trend="+1 w tym miesiącu" tone="blue"/><Stat icon={ListTodo} label="Otwarte zadania" value="8" foot="3 wymagają Twojej uwagi" trend="2 na dziś" tone="purple"/><Stat icon={Clock3} label="Śr. wykorzystanie budżetu" value="84%" foot={`Na podstawie ${projectList.length} projektów`} trend="6% vs. poprzedni m-c" tone="amber"/><Stat icon={Gauge} label="Zdrowie portfolio" value="92" suffix="/100" foot="Stabilnie · bez ryzyk krytycznych" trend="+4 pkt w tym tyg." tone="green"/></section>
   <section className="section-heading"><div><h2>Twoje projekty</h2><p>Monitoruj postęp i kondycję projektów</p></div><button className="text-button" onClick={()=>setSection('Projekty')}>Wszystkie projekty <ArrowRight size={15}/></button></section>
   <section className="project-grid">{filtered.map((p,i)=><ProjectCard key={p.client} project={p} index={i} onOpen={()=>notify(`Otwierasz projekt: ${p.name}`)}/>)}</section>
   <section className="bottom-grid"><div className="panel tasks-panel"><div className="panel-head"><div><h2>Do zrobienia</h2><p>Rzeczy, które wymagają Twojej uwagi</p></div><button className="more-button" onClick={()=>setSection('Zadania')}><Ellipsis size={18}/></button></div><div className="task-filters">{['Wszystkie','Dziś','Zaległe'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}{f==='Wszystkie'&&<span>{tasks.filter(t=>!t.done).length}</span>}</button>)}</div><div className="task-list">{visibleTasks.length?visibleTasks.map(task=><div className={`task-row ${task.done?'task-done':''}`} key={task.title}><button className={`check ${task.done?'checked':''}`} onClick={()=>toggleTask(task.index)} aria-label="Oznacz zadanie"><Check size={13}/></button><div className="task-main"><b>{task.title}</b><span>{task.project}</span></div><span className="task-due"><i className={task.due.startsWith('Dziś')?'due-today':''}/>{task.due}</span><div className={`avatar task-avatar avatar-${task.color}`}>{task.initials}</div><button className="task-menu" onClick={()=>notify('Opcje zadania')}><Ellipsis size={17}/></button></div>):<div className="empty-state">Brak zadań w tym widoku.</div>}</div><button className="all-tasks" onClick={()=>setSection('Zadania')}>Zobacz wszystkie zadania <ArrowRight size={14}/></button></div>
    <div className="panel activity-panel"><div className="panel-head"><div><h2>Ostatnia aktywność</h2><p>Co nowego w Twoim zespole</p></div><button className="more-button" onClick={()=>notify('Pełny dziennik aktywności')}><Ellipsis size={18}/></button></div><div className="activity-list">{updates.map((u,i)=><div className="activity-row" key={i}><div className={`avatar avatar-${u.tone}`}>{u.initials}</div><div className="activity-copy"><p><b>{u.who}</b> {u.action} <strong>{u.subject}</strong></p><span>{u.when}</span><div className="activity-note"><u.icon size={13}/>{u.text}</div></div></div>)}</div><button className="all-tasks" onClick={()=>notify('Pokazujesz całą aktywność')}>Cała aktywność <ArrowRight size={14}/></button></div>
   </section><footer><span>© 2026 Orbit Workspace</span><span><CircleHelp size={14}/> Centrum pomocy <i/> Status systemu: <b className="system-ok">● Operacyjny</b></span></footer></div>
  </main>
  {showModal&&<div className="modal-backdrop" onClick={()=>setShowModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowModal(false)}><X size={18}/></button><div className="modal-icon"><FolderKanban size={20}/></div><h2>Utwórz nowy projekt</h2><p>Dodaj projekt do workspace i zaproś zespół.</p><label>Nazwa projektu<input id="project-name" autoFocus placeholder="np. Aplikacja mobilna"/></label><label>Klient<input id="project-client" placeholder="Nazwa klienta"/></label><div className="modal-fields"><label>Typ projektu<select><option>Software development</option><option>Design</option><option>Consulting</option></select></label><label>Termin<select><option>Wybierz termin</option><option>1 miesiąc</option><option>3 miesiące</option></select></label></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setShowModal(false)}>Anuluj</button><button className="primary-button" onClick={()=>{const input=document.getElementById('project-name');if(!input.value.trim()){input.focus();return}const clientInput=document.getElementById('project-client');const client=clientInput.value.trim()||'NOWY KLIENT';setProjectList(prev=>[{client:client.toUpperCase(),name:input.value.trim(),tag:'Software project',stage:'Planning',progress:0,days:'Termin do ustalenia',initials:client.slice(0,2).toUpperCase(),tone:'blue',people:['PK'],budget:'—',status:'On track',statusTone:'green',date:'—'},...prev]);setShowModal(false);notify(`Projekt „${input.value.trim()}” został utworzony.`)}}><Plus size={16}/> Utwórz projekt</button></div></div></div>}
  {toast&&<div className="toast"><Check size={16}/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
 </div>
}
function Stat({icon:Icon,label,value,suffix,foot,trend,tone}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><i className={`stat-icon ${tone}`}><Icon size={17}/></i></div><div className="stat-value">{value}<small>{suffix}</small></div><div className="stat-bottom"><span>{foot}</span><span className={`stat-trend ${tone==='amber'?'amber-text':''}`}><ArrowDownRight size={13}/>{trend}</span></div></div>}
function ProjectCard({project:p,index,onOpen}){return <article className="project-card"><div className="project-card-top"><div className={`project-logo ${p.tone}`}>{p.initials}</div><div className="project-client"><span>{p.client}</span><b>{p.name}</b></div><button className="more-button" onClick={onOpen}><Ellipsis size={18}/></button></div><div className="project-meta"><span className="tag"><i/> {p.tag}</span><span className={`status ${p.statusTone}`}><i/> {p.status}</span></div><div className="progress-copy"><span>Postęp projektu</span><b>{p.progress}%</b></div><div className="progress-track"><i className={p.tone} style={{width:`${p.progress}%`}}/></div><div className="project-stage"><span>Aktualny etap</span><b>{p.stage}</b></div><div className="project-card-foot"><div className="avatar-stack">{p.people.map((person,i)=><div key={person} className={`avatar stack-avatar stack-${i}`}>{person}</div>)}<button className="add-person" onClick={onOpen}><Plus size={13}/></button></div><div className="project-foot-info"><span><ShieldAlert size={13}/> Budżet <b>{p.budget}</b></span><span><CalendarDays size={13}/> {p.days}</span></div></div></article>}
